### ISSUE TITLE
Browser version is not shown

### ISSUE THREAD

**Issue by rcaf** [hisorange/browser-detect#45] opened 2015-12-18 05:10 UTC
Hello,

I'm using Laravel 5.1.27

When I do this:

```
var_dump(\BrowserDetect::browserVersion());
```

I get a empty string.

Even if I do this: 
```
$browser = \BrowserDetect::detect()->toArray();
dd($browser);
```
The versions (major, minor, patch) of browser and os, it is always zero.

I tried this with Chrome, Firefox and Safari on a MacBook.

Or maybe this is normal when I see an application locally?

Thanks.

**Comment by hisorange** [comment] 2015-12-19 16:35
Nope, definitly not normal maybe something changed in 5.1, worked perfectly well in 5.0

**Comment by rcaf** [comment] 2015-12-29 05:56
I tested in 3 browsers: Chrome, Firefox, Safari.
The result is the same.

![captura de pantalla 2015-12-29 a las 2 54 07 a m](https://cloud.githubusercontent.com/assets/4222004/12030084/a2c175e6-add7-11e5-8f8c-ddbcf9e8e5ec.png)

**Comment by hisorange** [comment] 2015-12-29 11:05
Did you updated the browscap cache? If not you can active the autoupdate in the plugin config, just changed recently to be default true, maybe the cache is too old and only the browser family gets a match.

**Comment by rosesonfire** [comment] 2016-01-25 06:47
I am having the same problem. Could this issue be solved?

**Comment by hisorange** [comment] 2016-01-25 16:42
clear your browscap cache, if it's not solving it, than I need some exact data like,
+ User Agent string from your browser
+ Laravel version
+ package version

with that i can create a testing environment to reproduce the issue.

**Comment by lucidlemon** [comment] 2016-02-01 10:18
Can confirm this, no useable results whatsoever. It also does *not* download the browsecap.ini file or at least it does not save it into /cache/Browsecap.

UA: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2622.0 Safari/537.36`
Laravel version: `v5.1.28`
Package version: `2.0.2`

Set autoupdate within the settings to true. Configured the package in a correct way within config/app.php.

**Comment by hisorange** [comment] 2016-02-05 13:45
Manual download will not work, since the browscap converting the ini, will have to look into the browscap package to resolve this, thanks for the informations.

**Comment by BojanKogoj** [comment] 2016-02-17 09:50
As said, version numbers don't work. 
Laravel version: v5.1.29

BlackBerry 10 browser apparently returns "Safari" (which is no, even though it says so)

> Mozilla/5.0 (BB10; Touch) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.3.2.2639 Mobile Safari/537.35+

osFamily returns Win8.1 (and osVersion doesn't return anything)

> Mozilla/5.0 (Windows NT 6.3; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

And this is also without versions (in case it helps)

> Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by lucidlemon** [comment] 2016-02-17 10:27
It even turned out to go so far that it stopped my ecommerce webpage from working :)

```
exception 'ErrorException' with message 'file_get_contents(http://browscap.org/stream?q=Full_PHP_BrowsCapINI): failed to open stream: HTTP request failed! HTTP/1.1 429 Too Many Requests ' in /var/www/production/webshop/vendor/garetjax/phpbrowscap/src/phpbrowscap/Browscap.php:961 Stack trace: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_get_conten...', '/var/www/produc...', 961, Array) #1 /var/www/production/webshop/vendor/garetjax/phpbrowscap/src/phpbrowscap/Browscap.php(961): file_get_contents('http://browscap...', false, Resource id #9) #2 /var/www/production/webshop/vendor/garetjax/phpbrowscap/src/phpbrowscap/Browscap.php(815): phpbrowscap\Browscap->_getRemoteData('http://browscap...') #3 /var/www/production/webshop/vendor/garetjax/phpbrowscap/src/phpbrowscap/Browscap.php(501): phpbrowscap\Browscap->_getRemoteIniFile('http://browscap...', '/var/www/produc...') #4 /var/www/production/webshop/vendor/garetjax/phpbrowscap/src/phpbrowscap/Browscap.php(288): phpb
```

**Comment by BojanKogoj** [comment] 2016-02-17 10:49
Seems like a phpbrowscap doesn't work properly
```
    "browser_name" => "Mozilla/5.0 (BB10; Touch) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.3.2.2639 Mobile Safari/537.35+"
    "browser_name_regex" => "^mozilla/5\.0 \(bb10; touch\) applewebkit/.* \(khtml, like gecko\).*$"
    "browser_name_pattern" => "Mozilla/5.0 (BB10; Touch) AppleWebKit/* (KHTML, like Gecko)*"
    "Parent" => "BlackBerry"
    "Comment" => "BlackBerry"
    "Browser" => "BlackBerry"
    "Platform" => "BlackBerry OS"
    "Frames" => true
    "IFrames" => true
    "Tables" => true
    "Cookies" => true
    "JavaScript" => true
    "isMobileDevice" => true
    "CssVersion" => "2"
    "Device_Name" => "Blackberry"
    "Device_Maker" => "RIM"
    "Version" => "0.0"
    "MajorVer" => "0"
    "MinorVer" => "0"
    "Platform_Version" => "unknown"
    "Platform_Description" => "unknown"
    "Alpha" => false
    "Beta" => false
    "Win16" => false
    "Win32" => false
    "Win64" => false
    "BackgroundSounds" => false
    "VBScript" => false
    "JavaApplets" => false
    "ActiveXControls" => false
    "isSyndicationReader" => false
    "Crawler" => false
    "AolVersion" => "0"
    "RenderingEngine_Name" => "unknown"
    "RenderingEngine_Version" => "unknown"
```

**Comment by dzafel** [comment] 2016-05-19 09:41
Reported 6 months ago and still not fixed? I'm starting to think of a new library to use...

**Comment by hisorange** [comment] 2016-05-19 11:01
Sure, this project is basicly abadoned, I have no time to work on it, and is only up because it works perfectly fine under L4, I don't think it's going to be fixed in the near future, so if you have a better alternative use that, or send a fixing PR.

**Closed by hisorange** 2016-05-19 11:01 UTC

**Comment by Lvm-Daud** [comment] 2017-09-08 11:37
how to update browscap.ini file
